
// This file has been generated by the GUI designer. Do not modify.
namespace AkariSolver
{
	public partial class ErrorDialog
	{
		private global::Gtk.Frame ErrorFrame;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Label ErrorLabel1;
		
		private global::Gtk.Label ErrorLabel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AkariSolver.ErrorDialog
			this.Name = "AkariSolver.ErrorDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Error");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Internal child AkariSolver.ErrorDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.ErrorFrame = new global::Gtk.Frame ();
			this.ErrorFrame.Name = "ErrorFrame";
			this.ErrorFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child ErrorFrame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.ErrorLabel1 = new global::Gtk.Label ();
			this.ErrorLabel1.Name = "ErrorLabel1";
			this.ErrorLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("The puzzle is unsolvable!");
			this.GtkAlignment2.Add (this.ErrorLabel1);
			this.ErrorFrame.Add (this.GtkAlignment2);
			this.ErrorLabel = new global::Gtk.Label ();
			this.ErrorLabel.Name = "ErrorLabel";
			this.ErrorLabel.UseMarkup = true;
			this.ErrorFrame.LabelWidget = this.ErrorLabel;
			w1.Add (this.ErrorFrame);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.ErrorFrame]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child AkariSolver.ErrorDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 99;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
