
// This file has been generated by the GUI designer. Do not modify.
namespace AkariSolver
{
	public partial class GridConstructor
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.ScrolledWindow gridBoardWindow;
		
		private global::Gtk.TreeView gridBoard;
		
		private global::Gtk.Button buttonPlay;
		
		private global::Gtk.Button buttonHelp;
		
		private global::Gtk.Button buttonSolve;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AkariSolver.GridConstructor
			this.Name = "AkariSolver.GridConstructor";
			this.Title = global::Mono.Unix.Catalog.GetString ("Akari Grid");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.DefaultWidth = 400;
			this.DefaultHeight = 400;
			// Container child AkariSolver.GridConstructor.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.gridBoardWindow = new global::Gtk.ScrolledWindow ();
			this.gridBoardWindow.Name = "gridBoardWindow";
			this.gridBoardWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.gridBoardWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.gridBoardWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.gridBoardWindow.BorderWidth = ((uint)(10));
			// Container child gridBoardWindow.Gtk.Container+ContainerChild
			this.gridBoard = new global::Gtk.TreeView ();
			this.gridBoard.Name = "gridBoard";
			this.gridBoard.EnableSearch = false;
			this.gridBoard.HeadersVisible = false;
			this.gridBoardWindow.Add (this.gridBoard);
			this.fixed1.Add (this.gridBoardWindow);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.buttonPlay = new global::Gtk.Button ();
			this.buttonPlay.WidthRequest = 50;
			this.buttonPlay.CanFocus = true;
			this.buttonPlay.Name = "buttonPlay";
			this.buttonPlay.UseUnderline = true;
			this.buttonPlay.Label = global::Mono.Unix.Catalog.GetString ("Play!");
			this.fixed1.Add (this.buttonPlay);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonPlay]));
			w3.X = 187;
			w3.Y = 140;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.buttonHelp = new global::Gtk.Button ();
			this.buttonHelp.WidthRequest = 50;
			this.buttonHelp.CanFocus = true;
			this.buttonHelp.Name = "buttonHelp";
			this.buttonHelp.UseUnderline = true;
			this.buttonHelp.Label = global::Mono.Unix.Catalog.GetString ("Help");
			this.fixed1.Add (this.buttonHelp);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonHelp]));
			w4.X = 260;
			w4.Y = 212;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.buttonSolve = new global::Gtk.Button ();
			this.buttonSolve.WidthRequest = 50;
			this.buttonSolve.CanFocus = true;
			this.buttonSolve.Name = "buttonSolve";
			this.buttonSolve.UseUnderline = true;
			this.buttonSolve.Label = global::Mono.Unix.Catalog.GetString ("Solve");
			this.fixed1.Add (this.buttonSolve);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonSolve]));
			w5.X = 161;
			w5.Y = 224;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.buttonSolve.Hide ();
			this.Hide ();
			this.buttonPlay.Clicked += new global::System.EventHandler (this.OnButtonPlayClicked);
			this.buttonHelp.Clicked += new global::System.EventHandler (this.OnButtonHelpClicked);
			this.buttonSolve.Clicked += new global::System.EventHandler (this.OnButtonSolveClicked);
		}
	}
}
