
// This file has been generated by the GUI designer. Do not modify.
namespace AkariSolver
{
	public partial class HelpDialog
	{
		private global::Gtk.Frame RulesFrame;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview1;
		
		private global::Gtk.Label RulesFrameLabel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AkariSolver.HelpDialog
			this.Name = "AkariSolver.HelpDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Help");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Internal child AkariSolver.HelpDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.RulesFrame = new global::Gtk.Frame ();
			this.RulesFrame.Name = "RulesFrame";
			this.RulesFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child RulesFrame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = @"Rules of Akari:

	1. 	Lamps may be placed in any of the white 
		squares.
	2. 	The number in a hint square tells you how
		many lamps that may be placed next to it.
	3. 	Each lamp lights all white squares it can see
		both vertically and horizontally. Black squares
		block light.
	4.	Every white square must be lit.
	5. 	No lamp can light another lamp.

Building the Puzzle:

	- Clicking a cell will advance the black/hint square selection.
	- Right clicking a black/hint square will reset it to white.

Playing the Puzzle:

	- Clicking cells will place and clear lamps.
	- Right clicking cells will clear lamps.";
			this.textview1.Sensitive = false;
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textview1);
			this.GtkAlignment1.Add (this.GtkScrolledWindow);
			this.RulesFrame.Add (this.GtkAlignment1);
			this.RulesFrameLabel = new global::Gtk.Label ();
			this.RulesFrameLabel.Name = "RulesFrameLabel";
			this.RulesFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Help</b>");
			this.RulesFrameLabel.UseMarkup = true;
			this.RulesFrame.LabelWidget = this.RulesFrameLabel;
			w1.Add (this.RulesFrame);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.RulesFrame]));
			w5.Position = 0;
			// Internal child AkariSolver.HelpDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 287;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
