
// This file has been generated by the GUI designer. Do not modify.
namespace AkariSolver
{
	public partial class VictoryDialog
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Button ButtonOK;
		
		private global::Gtk.Button ButtonAgain;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AkariSolver.VictoryDialog
			this.Name = "AkariSolver.VictoryDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Victory!");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Internal child AkariSolver.VictoryDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Congratulations!");
			this.GtkAlignment.Add (this.label1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>You Won!</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			w1.Add (this.frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.frame1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child AkariSolver.VictoryDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ButtonOK = new global::Gtk.Button ();
			this.ButtonOK.WidthRequest = 50;
			this.ButtonOK.CanFocus = true;
			this.ButtonOK.Name = "ButtonOK";
			this.ButtonOK.UseUnderline = true;
			this.ButtonOK.Label = global::Mono.Unix.Catalog.GetString ("OK");
			this.AddActionWidget (this.ButtonOK, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.ButtonOK]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ButtonAgain = new global::Gtk.Button ();
			this.ButtonAgain.WidthRequest = 50;
			this.ButtonAgain.CanFocus = true;
			this.ButtonAgain.Name = "ButtonAgain";
			this.ButtonAgain.UseUnderline = true;
			this.ButtonAgain.Label = global::Mono.Unix.Catalog.GetString ("New Grid");
			this.AddActionWidget (this.ButtonAgain, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.ButtonAgain]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 101;
			this.Show ();
			this.ButtonOK.Clicked += new global::System.EventHandler (this.OnButtonOKClicked);
			this.ButtonAgain.Clicked += new global::System.EventHandler (this.OnButtonAgainClicked);
		}
	}
}
